name: API Linting
run-name: 🚀
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17'
      - name: Install dependencies
        run: npm install -g @stoplight/spectral-cli
